/**
 * Remembers and retrieves a value by a given key, or the value generated by `getValue` if the key doesn't exist.
 * The return type is inferred from the return type of `getValue`.
 *
 * @template T
 * @param {string} key - The key under which to remember the value.
 * @param {() => T} getValue - The function that generates the value to remember.
 * @returns {NonNullable<T>} - The remembered value.
 */
export const remember = <T>(key: string, getValue: () => T): NonNullable<T> => {
  const g = globalThis as typeof globalThis & { __singletons__?: Map<string, T> | undefined };
  g.__singletons__ ??= new Map();
  if (!g.__singletons__.has(key)) g.__singletons__.set(key, getValue());
  return g.__singletons__.get(key) as NonNullable<T>;
};

/**
 * Forgets a remembered value by a given key. Does not throw if the key doesn't exist.
 *
 * @param {string} key - The key under which the value was remembered.
 * @return {boolean} - A remembered value existed and has been forgotten.
 */
export const forget = (key: string): boolean => {
  const g = globalThis as typeof globalThis & { __singletons__?: Map<string, unknown> | undefined };
  g.__singletons__ ??= new Map();
  return g.__singletons__.delete(key);
};
