query GetInvoices {
  invoices {
    id
    tag
    paymentDue
    clientName
    status
    total
  }
}

query GetInvoice($where: UniqueIdInput!) {
  invoice(where: $where) {
    userId
    createdAt
    issueDate
    paymentDue
    tag
    description
    paymentTerms
    clientName
    clientEmail
    status
    senderAddress {
      street
      city
      postCode
      country
    }
    clientAddress {
      street
      city
      postCode
      country
    }
    total
    items {
      id
      name
      price
      quantity
      total
    }
  }
}

mutation CreateInvoice($input: CreateInvoiceInput!) {
  createInvoice(input: $input) {
    id
    tag
    paymentDue
    clientName
    status
    total
  }
}

mutation UpdateInvoice($input: UpdateInvoiceInput!, $where: UniqueIdInput!) {
  updateInvoice(input: $input, where: $where) {
    issueDate
    paymentDue
    tag
    description
    paymentTerms
    clientName
    clientEmail
    status
    senderAddress {
      street
      city
      postCode
      country
    }
    clientAddress {
      street
      city
      postCode
      country
    }
    total
    items {
      id
      name
      quantity
      price
      total
    }
  }
}

mutation DeleteInvoice($where: UniqueIdInput!) {
  deleteInvoice(where: $where) {
    id
  }
}
