query GetUser {
  user {
    id
    photo
    email
  }
}

mutation Register($input: RegisterInput!) {
  register(input: $input) {
    accessToken
    user {
      id
      photo
    }
  }
}

mutation Login($input: LoginInput!) {
  login(input: $input) {
    accessToken
    user {
      id
      photo
    }
  }
}

query RefreshAuth {
  refreshAuth {
    accessToken
  }
}

mutation Logout {
  logout {
    message
  }
}
