mutation Register($input: RegisterInput!) {
  register(input: $input) {
    message
  }
}

mutation Login($input: LoginInput!) {
  login(input: $input) {
    token
  }
}

query Refresh {
  refresh {
    token
  }
}

query Logout {
  logout {
    message
  }
}
