
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Address` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Address
 * 
 */
export type AddressModel = runtime.Types.Result.DefaultSelection<Prisma.$AddressPayload>






export type AddressCompositeFilter = {
  equals?: Prisma.AddressObjectEqualityInput
  is?: Prisma.AddressWhereInput
  isNot?: Prisma.AddressWhereInput
}

export type AddressOrderByInput = {
  street?: Prisma.SortOrder
  city?: Prisma.SortOrder
  postCode?: Prisma.SortOrder
  country?: Prisma.SortOrder
}

export type AddressCreateEnvelopeInput = {
  set?: Prisma.AddressCreateInput
}

export type AddressUpdateEnvelopeInput = {
  set?: Prisma.AddressCreateInput
  update?: Prisma.AddressUpdateInput
}

export type AddressWhereInput = {
  AND?: Prisma.AddressWhereInput | Prisma.AddressWhereInput[]
  OR?: Prisma.AddressWhereInput[]
  NOT?: Prisma.AddressWhereInput | Prisma.AddressWhereInput[]
  street?: Prisma.StringFilter<"Address"> | string
  city?: Prisma.StringFilter<"Address"> | string
  postCode?: Prisma.StringFilter<"Address"> | string
  country?: Prisma.StringFilter<"Address"> | string
}

export type AddressUpdateInput = {
  street?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  postCode?: Prisma.StringFieldUpdateOperationsInput | string
  country?: Prisma.StringFieldUpdateOperationsInput | string
}



export type AddressSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  street?: boolean
  city?: boolean
  postCode?: boolean
  country?: boolean
}, ExtArgs["result"]["address"]>



export type AddressSelectScalar = {
  street?: boolean
  city?: boolean
  postCode?: boolean
  country?: boolean
}

export type AddressOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"street" | "city" | "postCode" | "country", ExtArgs["result"]["address"]>

export type $AddressPayload = {
  name: "Address"
  objects: {}
  scalars: {
    street: string
    city: string
    postCode: string
    country: string
  }
  composites: {}
}

export type AddressGetPayload<S extends boolean | null | undefined | AddressDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AddressPayload, S>





/**
 * Fields of the Address model
 */
export interface AddressFieldRefs {
  readonly street: Prisma.FieldRef<"Address", 'String'>
  readonly city: Prisma.FieldRef<"Address", 'String'>
  readonly postCode: Prisma.FieldRef<"Address", 'String'>
  readonly country: Prisma.FieldRef<"Address", 'String'>
}
    

// Custom InputTypes
/**
 * Address without action
 */
export type AddressDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Address
   */
  select?: Prisma.AddressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Address
   */
  omit?: Prisma.AddressOmit<ExtArgs> | null
}
