
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Invoice` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Invoice
 * 
 */
export type InvoiceModel = runtime.Types.Result.DefaultSelection<Prisma.$InvoicePayload>

export type AggregateInvoice = {
  _count: InvoiceCountAggregateOutputType | null
  _avg: InvoiceAvgAggregateOutputType | null
  _sum: InvoiceSumAggregateOutputType | null
  _min: InvoiceMinAggregateOutputType | null
  _max: InvoiceMaxAggregateOutputType | null
}

export type InvoiceAvgAggregateOutputType = {
  paymentTerms: number | null
  total: number | null
}

export type InvoiceSumAggregateOutputType = {
  paymentTerms: number | null
  total: number | null
}

export type InvoiceMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  slug: string | null
  paymentDue: Date | null
  paymentTerms: number | null
  status: string | null
  total: number | null
  clientName: string | null
  clientEmail: string | null
  issued: Date | null
  description: string | null
  userId: string | null
}

export type InvoiceMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  slug: string | null
  paymentDue: Date | null
  paymentTerms: number | null
  status: string | null
  total: number | null
  clientName: string | null
  clientEmail: string | null
  issued: Date | null
  description: string | null
  userId: string | null
}

export type InvoiceCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  slug: number
  paymentDue: number
  paymentTerms: number
  status: number
  total: number
  clientName: number
  clientEmail: number
  issued: number
  description: number
  userId: number
  _all: number
}


export type InvoiceAvgAggregateInputType = {
  paymentTerms?: true
  total?: true
}

export type InvoiceSumAggregateInputType = {
  paymentTerms?: true
  total?: true
}

export type InvoiceMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  slug?: true
  paymentDue?: true
  paymentTerms?: true
  status?: true
  total?: true
  clientName?: true
  clientEmail?: true
  issued?: true
  description?: true
  userId?: true
}

export type InvoiceMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  slug?: true
  paymentDue?: true
  paymentTerms?: true
  status?: true
  total?: true
  clientName?: true
  clientEmail?: true
  issued?: true
  description?: true
  userId?: true
}

export type InvoiceCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  slug?: true
  paymentDue?: true
  paymentTerms?: true
  status?: true
  total?: true
  clientName?: true
  clientEmail?: true
  issued?: true
  description?: true
  userId?: true
  _all?: true
}

export type InvoiceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Invoice to aggregate.
   */
  where?: Prisma.InvoiceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Invoices to fetch.
   */
  orderBy?: Prisma.InvoiceOrderByWithRelationInput | Prisma.InvoiceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.InvoiceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Invoices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Invoices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Invoices
  **/
  _count?: true | InvoiceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: InvoiceAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: InvoiceSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: InvoiceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: InvoiceMaxAggregateInputType
}

export type GetInvoiceAggregateType<T extends InvoiceAggregateArgs> = {
      [P in keyof T & keyof AggregateInvoice]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateInvoice[P]>
    : Prisma.GetScalarType<T[P], AggregateInvoice[P]>
}




export type InvoiceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InvoiceWhereInput
  orderBy?: Prisma.InvoiceOrderByWithAggregationInput | Prisma.InvoiceOrderByWithAggregationInput[]
  by: Prisma.InvoiceScalarFieldEnum[] | Prisma.InvoiceScalarFieldEnum
  having?: Prisma.InvoiceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: InvoiceCountAggregateInputType | true
  _avg?: InvoiceAvgAggregateInputType
  _sum?: InvoiceSumAggregateInputType
  _min?: InvoiceMinAggregateInputType
  _max?: InvoiceMaxAggregateInputType
}

export type InvoiceGroupByOutputType = {
  id: string
  createdAt: Date
  updatedAt: Date
  slug: string
  paymentDue: Date
  paymentTerms: number
  status: string | null
  total: number
  clientName: string
  clientEmail: string
  issued: Date
  description: string
  userId: string | null
  _count: InvoiceCountAggregateOutputType | null
  _avg: InvoiceAvgAggregateOutputType | null
  _sum: InvoiceSumAggregateOutputType | null
  _min: InvoiceMinAggregateOutputType | null
  _max: InvoiceMaxAggregateOutputType | null
}

type GetInvoiceGroupByPayload<T extends InvoiceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<InvoiceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof InvoiceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], InvoiceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], InvoiceGroupByOutputType[P]>
      }
    >
  >



export type InvoiceWhereInput = {
  AND?: Prisma.InvoiceWhereInput | Prisma.InvoiceWhereInput[]
  OR?: Prisma.InvoiceWhereInput[]
  NOT?: Prisma.InvoiceWhereInput | Prisma.InvoiceWhereInput[]
  id?: Prisma.StringFilter<"Invoice"> | string
  createdAt?: Prisma.DateTimeFilter<"Invoice"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Invoice"> | Date | string
  slug?: Prisma.StringFilter<"Invoice"> | string
  paymentDue?: Prisma.DateTimeFilter<"Invoice"> | Date | string
  paymentTerms?: Prisma.IntFilter<"Invoice"> | number
  status?: Prisma.StringNullableFilter<"Invoice"> | string | null
  total?: Prisma.FloatFilter<"Invoice"> | number
  clientName?: Prisma.StringFilter<"Invoice"> | string
  clientEmail?: Prisma.StringFilter<"Invoice"> | string
  clientAddress?: Prisma.XOR<Prisma.AddressCompositeFilter, Prisma.AddressObjectEqualityInput>
  senderAddress?: Prisma.XOR<Prisma.AddressCompositeFilter, Prisma.AddressObjectEqualityInput>
  issued?: Prisma.DateTimeFilter<"Invoice"> | Date | string
  description?: Prisma.StringFilter<"Invoice"> | string
  items?: Prisma.InvoiceItemCompositeListFilter | Prisma.InvoiceItemObjectEqualityInput[]
  userId?: Prisma.StringNullableFilter<"Invoice"> | string | null
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type InvoiceOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  paymentDue?: Prisma.SortOrder
  paymentTerms?: Prisma.SortOrder
  status?: Prisma.SortOrder
  total?: Prisma.SortOrder
  clientName?: Prisma.SortOrder
  clientEmail?: Prisma.SortOrder
  clientAddress?: Prisma.AddressOrderByInput
  senderAddress?: Prisma.AddressOrderByInput
  issued?: Prisma.SortOrder
  description?: Prisma.SortOrder
  items?: Prisma.InvoiceItemOrderByCompositeAggregateInput
  userId?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type InvoiceWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  slug?: string
  AND?: Prisma.InvoiceWhereInput | Prisma.InvoiceWhereInput[]
  OR?: Prisma.InvoiceWhereInput[]
  NOT?: Prisma.InvoiceWhereInput | Prisma.InvoiceWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"Invoice"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Invoice"> | Date | string
  paymentDue?: Prisma.DateTimeFilter<"Invoice"> | Date | string
  paymentTerms?: Prisma.IntFilter<"Invoice"> | number
  status?: Prisma.StringNullableFilter<"Invoice"> | string | null
  total?: Prisma.FloatFilter<"Invoice"> | number
  clientName?: Prisma.StringFilter<"Invoice"> | string
  clientEmail?: Prisma.StringFilter<"Invoice"> | string
  clientAddress?: Prisma.XOR<Prisma.AddressCompositeFilter, Prisma.AddressObjectEqualityInput>
  senderAddress?: Prisma.XOR<Prisma.AddressCompositeFilter, Prisma.AddressObjectEqualityInput>
  issued?: Prisma.DateTimeFilter<"Invoice"> | Date | string
  description?: Prisma.StringFilter<"Invoice"> | string
  items?: Prisma.InvoiceItemCompositeListFilter | Prisma.InvoiceItemObjectEqualityInput[]
  userId?: Prisma.StringNullableFilter<"Invoice"> | string | null
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id" | "slug">

export type InvoiceOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  paymentDue?: Prisma.SortOrder
  paymentTerms?: Prisma.SortOrder
  status?: Prisma.SortOrder
  total?: Prisma.SortOrder
  clientName?: Prisma.SortOrder
  clientEmail?: Prisma.SortOrder
  issued?: Prisma.SortOrder
  description?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  _count?: Prisma.InvoiceCountOrderByAggregateInput
  _avg?: Prisma.InvoiceAvgOrderByAggregateInput
  _max?: Prisma.InvoiceMaxOrderByAggregateInput
  _min?: Prisma.InvoiceMinOrderByAggregateInput
  _sum?: Prisma.InvoiceSumOrderByAggregateInput
}

export type InvoiceScalarWhereWithAggregatesInput = {
  AND?: Prisma.InvoiceScalarWhereWithAggregatesInput | Prisma.InvoiceScalarWhereWithAggregatesInput[]
  OR?: Prisma.InvoiceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.InvoiceScalarWhereWithAggregatesInput | Prisma.InvoiceScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Invoice"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Invoice"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Invoice"> | Date | string
  slug?: Prisma.StringWithAggregatesFilter<"Invoice"> | string
  paymentDue?: Prisma.DateTimeWithAggregatesFilter<"Invoice"> | Date | string
  paymentTerms?: Prisma.IntWithAggregatesFilter<"Invoice"> | number
  status?: Prisma.StringNullableWithAggregatesFilter<"Invoice"> | string | null
  total?: Prisma.FloatWithAggregatesFilter<"Invoice"> | number
  clientName?: Prisma.StringWithAggregatesFilter<"Invoice"> | string
  clientEmail?: Prisma.StringWithAggregatesFilter<"Invoice"> | string
  issued?: Prisma.DateTimeWithAggregatesFilter<"Invoice"> | Date | string
  description?: Prisma.StringWithAggregatesFilter<"Invoice"> | string
  userId?: Prisma.StringNullableWithAggregatesFilter<"Invoice"> | string | null
}

export type InvoiceCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  slug: string
  paymentDue: Date | string
  paymentTerms: number
  status?: string | null
  total: number
  clientName: string
  clientEmail: string
  clientAddress: Prisma.XOR<Prisma.AddressCreateEnvelopeInput, Prisma.AddressCreateInput>
  senderAddress: Prisma.XOR<Prisma.AddressCreateEnvelopeInput, Prisma.AddressCreateInput>
  issued: Date | string
  description: string
  items?: Prisma.XOR<Prisma.InvoiceItemListCreateEnvelopeInput, Prisma.InvoiceItemCreateInput> | Prisma.InvoiceItemCreateInput[]
  user?: Prisma.UserCreateNestedOneWithoutInvoiceInput
}

export type InvoiceUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  slug: string
  paymentDue: Date | string
  paymentTerms: number
  status?: string | null
  total: number
  clientName: string
  clientEmail: string
  clientAddress: Prisma.XOR<Prisma.AddressCreateEnvelopeInput, Prisma.AddressCreateInput>
  senderAddress: Prisma.XOR<Prisma.AddressCreateEnvelopeInput, Prisma.AddressCreateInput>
  issued: Date | string
  description: string
  items?: Prisma.XOR<Prisma.InvoiceItemListCreateEnvelopeInput, Prisma.InvoiceItemCreateInput> | Prisma.InvoiceItemCreateInput[]
  userId?: string | null
}

export type InvoiceUpdateInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  paymentDue?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paymentTerms?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.FloatFieldUpdateOperationsInput | number
  clientName?: Prisma.StringFieldUpdateOperationsInput | string
  clientEmail?: Prisma.StringFieldUpdateOperationsInput | string
  clientAddress?: Prisma.XOR<Prisma.AddressUpdateEnvelopeInput, Prisma.AddressCreateInput>
  senderAddress?: Prisma.XOR<Prisma.AddressUpdateEnvelopeInput, Prisma.AddressCreateInput>
  issued?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  items?: Prisma.XOR<Prisma.InvoiceItemListUpdateEnvelopeInput, Prisma.InvoiceItemCreateInput> | Prisma.InvoiceItemCreateInput[]
  user?: Prisma.UserUpdateOneWithoutInvoiceNestedInput
}

export type InvoiceUncheckedUpdateInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  paymentDue?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paymentTerms?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.FloatFieldUpdateOperationsInput | number
  clientName?: Prisma.StringFieldUpdateOperationsInput | string
  clientEmail?: Prisma.StringFieldUpdateOperationsInput | string
  clientAddress?: Prisma.XOR<Prisma.AddressUpdateEnvelopeInput, Prisma.AddressCreateInput>
  senderAddress?: Prisma.XOR<Prisma.AddressUpdateEnvelopeInput, Prisma.AddressCreateInput>
  issued?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  items?: Prisma.XOR<Prisma.InvoiceItemListUpdateEnvelopeInput, Prisma.InvoiceItemCreateInput> | Prisma.InvoiceItemCreateInput[]
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type InvoiceCreateManyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  slug: string
  paymentDue: Date | string
  paymentTerms: number
  status?: string | null
  total: number
  clientName: string
  clientEmail: string
  clientAddress: Prisma.XOR<Prisma.AddressCreateEnvelopeInput, Prisma.AddressCreateInput>
  senderAddress: Prisma.XOR<Prisma.AddressCreateEnvelopeInput, Prisma.AddressCreateInput>
  issued: Date | string
  description: string
  items?: Prisma.XOR<Prisma.InvoiceItemListCreateEnvelopeInput, Prisma.InvoiceItemCreateInput> | Prisma.InvoiceItemCreateInput[]
  userId?: string | null
}

export type InvoiceUpdateManyMutationInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  paymentDue?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paymentTerms?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.FloatFieldUpdateOperationsInput | number
  clientName?: Prisma.StringFieldUpdateOperationsInput | string
  clientEmail?: Prisma.StringFieldUpdateOperationsInput | string
  clientAddress?: Prisma.XOR<Prisma.AddressUpdateEnvelopeInput, Prisma.AddressCreateInput>
  senderAddress?: Prisma.XOR<Prisma.AddressUpdateEnvelopeInput, Prisma.AddressCreateInput>
  issued?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  items?: Prisma.XOR<Prisma.InvoiceItemListUpdateEnvelopeInput, Prisma.InvoiceItemCreateInput> | Prisma.InvoiceItemCreateInput[]
}

export type InvoiceUncheckedUpdateManyInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  paymentDue?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paymentTerms?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.FloatFieldUpdateOperationsInput | number
  clientName?: Prisma.StringFieldUpdateOperationsInput | string
  clientEmail?: Prisma.StringFieldUpdateOperationsInput | string
  clientAddress?: Prisma.XOR<Prisma.AddressUpdateEnvelopeInput, Prisma.AddressCreateInput>
  senderAddress?: Prisma.XOR<Prisma.AddressUpdateEnvelopeInput, Prisma.AddressCreateInput>
  issued?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  items?: Prisma.XOR<Prisma.InvoiceItemListUpdateEnvelopeInput, Prisma.InvoiceItemCreateInput> | Prisma.InvoiceItemCreateInput[]
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type InvoiceListRelationFilter = {
  every?: Prisma.InvoiceWhereInput
  some?: Prisma.InvoiceWhereInput
  none?: Prisma.InvoiceWhereInput
}

export type InvoiceOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AddressObjectEqualityInput = {
  street: string
  city: string
  postCode: string
  country: string
}

export type InvoiceItemObjectEqualityInput = {
  id: string
  name: string
  quantity: number
  price: number
  total: number
}

export type InvoiceCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  paymentDue?: Prisma.SortOrder
  paymentTerms?: Prisma.SortOrder
  status?: Prisma.SortOrder
  total?: Prisma.SortOrder
  clientName?: Prisma.SortOrder
  clientEmail?: Prisma.SortOrder
  issued?: Prisma.SortOrder
  description?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type InvoiceAvgOrderByAggregateInput = {
  paymentTerms?: Prisma.SortOrder
  total?: Prisma.SortOrder
}

export type InvoiceMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  paymentDue?: Prisma.SortOrder
  paymentTerms?: Prisma.SortOrder
  status?: Prisma.SortOrder
  total?: Prisma.SortOrder
  clientName?: Prisma.SortOrder
  clientEmail?: Prisma.SortOrder
  issued?: Prisma.SortOrder
  description?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type InvoiceMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  paymentDue?: Prisma.SortOrder
  paymentTerms?: Prisma.SortOrder
  status?: Prisma.SortOrder
  total?: Prisma.SortOrder
  clientName?: Prisma.SortOrder
  clientEmail?: Prisma.SortOrder
  issued?: Prisma.SortOrder
  description?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type InvoiceSumOrderByAggregateInput = {
  paymentTerms?: Prisma.SortOrder
  total?: Prisma.SortOrder
}

export type InvoiceCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.InvoiceCreateWithoutUserInput, Prisma.InvoiceUncheckedCreateWithoutUserInput> | Prisma.InvoiceCreateWithoutUserInput[] | Prisma.InvoiceUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.InvoiceCreateOrConnectWithoutUserInput | Prisma.InvoiceCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.InvoiceCreateManyUserInputEnvelope
  connect?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
}

export type InvoiceUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.InvoiceCreateWithoutUserInput, Prisma.InvoiceUncheckedCreateWithoutUserInput> | Prisma.InvoiceCreateWithoutUserInput[] | Prisma.InvoiceUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.InvoiceCreateOrConnectWithoutUserInput | Prisma.InvoiceCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.InvoiceCreateManyUserInputEnvelope
  connect?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
}

export type InvoiceUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.InvoiceCreateWithoutUserInput, Prisma.InvoiceUncheckedCreateWithoutUserInput> | Prisma.InvoiceCreateWithoutUserInput[] | Prisma.InvoiceUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.InvoiceCreateOrConnectWithoutUserInput | Prisma.InvoiceCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.InvoiceUpsertWithWhereUniqueWithoutUserInput | Prisma.InvoiceUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.InvoiceCreateManyUserInputEnvelope
  set?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  disconnect?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  delete?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  connect?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  update?: Prisma.InvoiceUpdateWithWhereUniqueWithoutUserInput | Prisma.InvoiceUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.InvoiceUpdateManyWithWhereWithoutUserInput | Prisma.InvoiceUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.InvoiceScalarWhereInput | Prisma.InvoiceScalarWhereInput[]
}

export type InvoiceUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.InvoiceCreateWithoutUserInput, Prisma.InvoiceUncheckedCreateWithoutUserInput> | Prisma.InvoiceCreateWithoutUserInput[] | Prisma.InvoiceUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.InvoiceCreateOrConnectWithoutUserInput | Prisma.InvoiceCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.InvoiceUpsertWithWhereUniqueWithoutUserInput | Prisma.InvoiceUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.InvoiceCreateManyUserInputEnvelope
  set?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  disconnect?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  delete?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  connect?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  update?: Prisma.InvoiceUpdateWithWhereUniqueWithoutUserInput | Prisma.InvoiceUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.InvoiceUpdateManyWithWhereWithoutUserInput | Prisma.InvoiceUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.InvoiceScalarWhereInput | Prisma.InvoiceScalarWhereInput[]
}

export type AddressCreateInput = {
  street: string
  city: string
  postCode: string
  country: string
}

export type InvoiceItemCreateInput = {
  id: string
  name: string
  quantity: number
  price: number
  total: number
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
  unset?: boolean
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type InvoiceCreateWithoutUserInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  slug: string
  paymentDue: Date | string
  paymentTerms: number
  status?: string | null
  total: number
  clientName: string
  clientEmail: string
  clientAddress: Prisma.XOR<Prisma.AddressCreateEnvelopeInput, Prisma.AddressCreateInput>
  senderAddress: Prisma.XOR<Prisma.AddressCreateEnvelopeInput, Prisma.AddressCreateInput>
  issued: Date | string
  description: string
  items?: Prisma.XOR<Prisma.InvoiceItemListCreateEnvelopeInput, Prisma.InvoiceItemCreateInput> | Prisma.InvoiceItemCreateInput[]
}

export type InvoiceUncheckedCreateWithoutUserInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  slug: string
  paymentDue: Date | string
  paymentTerms: number
  status?: string | null
  total: number
  clientName: string
  clientEmail: string
  clientAddress: Prisma.XOR<Prisma.AddressCreateEnvelopeInput, Prisma.AddressCreateInput>
  senderAddress: Prisma.XOR<Prisma.AddressCreateEnvelopeInput, Prisma.AddressCreateInput>
  issued: Date | string
  description: string
  items?: Prisma.XOR<Prisma.InvoiceItemListCreateEnvelopeInput, Prisma.InvoiceItemCreateInput> | Prisma.InvoiceItemCreateInput[]
}

export type InvoiceCreateOrConnectWithoutUserInput = {
  where: Prisma.InvoiceWhereUniqueInput
  create: Prisma.XOR<Prisma.InvoiceCreateWithoutUserInput, Prisma.InvoiceUncheckedCreateWithoutUserInput>
}

export type InvoiceCreateManyUserInputEnvelope = {
  data: Prisma.InvoiceCreateManyUserInput | Prisma.InvoiceCreateManyUserInput[]
}

export type InvoiceUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.InvoiceWhereUniqueInput
  update: Prisma.XOR<Prisma.InvoiceUpdateWithoutUserInput, Prisma.InvoiceUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.InvoiceCreateWithoutUserInput, Prisma.InvoiceUncheckedCreateWithoutUserInput>
}

export type InvoiceUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.InvoiceWhereUniqueInput
  data: Prisma.XOR<Prisma.InvoiceUpdateWithoutUserInput, Prisma.InvoiceUncheckedUpdateWithoutUserInput>
}

export type InvoiceUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.InvoiceScalarWhereInput
  data: Prisma.XOR<Prisma.InvoiceUpdateManyMutationInput, Prisma.InvoiceUncheckedUpdateManyWithoutUserInput>
}

export type InvoiceScalarWhereInput = {
  AND?: Prisma.InvoiceScalarWhereInput | Prisma.InvoiceScalarWhereInput[]
  OR?: Prisma.InvoiceScalarWhereInput[]
  NOT?: Prisma.InvoiceScalarWhereInput | Prisma.InvoiceScalarWhereInput[]
  id?: Prisma.StringFilter<"Invoice"> | string
  createdAt?: Prisma.DateTimeFilter<"Invoice"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Invoice"> | Date | string
  slug?: Prisma.StringFilter<"Invoice"> | string
  paymentDue?: Prisma.DateTimeFilter<"Invoice"> | Date | string
  paymentTerms?: Prisma.IntFilter<"Invoice"> | number
  status?: Prisma.StringNullableFilter<"Invoice"> | string | null
  total?: Prisma.FloatFilter<"Invoice"> | number
  clientName?: Prisma.StringFilter<"Invoice"> | string
  clientEmail?: Prisma.StringFilter<"Invoice"> | string
  issued?: Prisma.DateTimeFilter<"Invoice"> | Date | string
  description?: Prisma.StringFilter<"Invoice"> | string
  userId?: Prisma.StringNullableFilter<"Invoice"> | string | null
}

export type InvoiceCreateManyUserInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  slug: string
  paymentDue: Date | string
  paymentTerms: number
  status?: string | null
  total: number
  clientName: string
  clientEmail: string
  clientAddress: Prisma.XOR<Prisma.AddressCreateEnvelopeInput, Prisma.AddressCreateInput>
  senderAddress: Prisma.XOR<Prisma.AddressCreateEnvelopeInput, Prisma.AddressCreateInput>
  issued: Date | string
  description: string
  items?: Prisma.XOR<Prisma.InvoiceItemListCreateEnvelopeInput, Prisma.InvoiceItemCreateInput> | Prisma.InvoiceItemCreateInput[]
}

export type InvoiceUpdateWithoutUserInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  paymentDue?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paymentTerms?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.FloatFieldUpdateOperationsInput | number
  clientName?: Prisma.StringFieldUpdateOperationsInput | string
  clientEmail?: Prisma.StringFieldUpdateOperationsInput | string
  clientAddress?: Prisma.XOR<Prisma.AddressUpdateEnvelopeInput, Prisma.AddressCreateInput>
  senderAddress?: Prisma.XOR<Prisma.AddressUpdateEnvelopeInput, Prisma.AddressCreateInput>
  issued?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  items?: Prisma.XOR<Prisma.InvoiceItemListUpdateEnvelopeInput, Prisma.InvoiceItemCreateInput> | Prisma.InvoiceItemCreateInput[]
}

export type InvoiceUncheckedUpdateWithoutUserInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  paymentDue?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paymentTerms?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.FloatFieldUpdateOperationsInput | number
  clientName?: Prisma.StringFieldUpdateOperationsInput | string
  clientEmail?: Prisma.StringFieldUpdateOperationsInput | string
  clientAddress?: Prisma.XOR<Prisma.AddressUpdateEnvelopeInput, Prisma.AddressCreateInput>
  senderAddress?: Prisma.XOR<Prisma.AddressUpdateEnvelopeInput, Prisma.AddressCreateInput>
  issued?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  items?: Prisma.XOR<Prisma.InvoiceItemListUpdateEnvelopeInput, Prisma.InvoiceItemCreateInput> | Prisma.InvoiceItemCreateInput[]
}

export type InvoiceUncheckedUpdateManyWithoutUserInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  paymentDue?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paymentTerms?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.FloatFieldUpdateOperationsInput | number
  clientName?: Prisma.StringFieldUpdateOperationsInput | string
  clientEmail?: Prisma.StringFieldUpdateOperationsInput | string
  clientAddress?: Prisma.XOR<Prisma.AddressUpdateEnvelopeInput, Prisma.AddressCreateInput>
  senderAddress?: Prisma.XOR<Prisma.AddressUpdateEnvelopeInput, Prisma.AddressCreateInput>
  issued?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  items?: Prisma.XOR<Prisma.InvoiceItemListUpdateEnvelopeInput, Prisma.InvoiceItemCreateInput> | Prisma.InvoiceItemCreateInput[]
}



export type InvoiceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  slug?: boolean
  paymentDue?: boolean
  paymentTerms?: boolean
  status?: boolean
  total?: boolean
  clientName?: boolean
  clientEmail?: boolean
  clientAddress?: boolean | Prisma.AddressDefaultArgs<ExtArgs>
  senderAddress?: boolean | Prisma.AddressDefaultArgs<ExtArgs>
  issued?: boolean
  description?: boolean
  items?: boolean | Prisma.InvoiceItemDefaultArgs<ExtArgs>
  userId?: boolean
  user?: boolean | Prisma.Invoice$userArgs<ExtArgs>
}, ExtArgs["result"]["invoice"]>



export type InvoiceSelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  slug?: boolean
  paymentDue?: boolean
  paymentTerms?: boolean
  status?: boolean
  total?: boolean
  clientName?: boolean
  clientEmail?: boolean
  issued?: boolean
  description?: boolean
  userId?: boolean
}

export type InvoiceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "slug" | "paymentDue" | "paymentTerms" | "status" | "total" | "clientName" | "clientEmail" | "clientAddress" | "senderAddress" | "issued" | "description" | "items" | "userId", ExtArgs["result"]["invoice"]>
export type InvoiceInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.Invoice$userArgs<ExtArgs>
}

export type $InvoicePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Invoice"
  objects: {
    user: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    updatedAt: Date
    slug: string
    paymentDue: Date
    paymentTerms: number
    status: string | null
    total: number
    clientName: string
    clientEmail: string
    issued: Date
    description: string
    userId: string | null
  }, ExtArgs["result"]["invoice"]>
  composites: {
    clientAddress: Prisma.$AddressPayload
    senderAddress: Prisma.$AddressPayload
    items: Prisma.$InvoiceItemPayload[]
  }
}

export type InvoiceGetPayload<S extends boolean | null | undefined | InvoiceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$InvoicePayload, S>

export type InvoiceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<InvoiceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: InvoiceCountAggregateInputType | true
  }

export interface InvoiceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Invoice'], meta: { name: 'Invoice' } }
  /**
   * Find zero or one Invoice that matches the filter.
   * @param {InvoiceFindUniqueArgs} args - Arguments to find a Invoice
   * @example
   * // Get one Invoice
   * const invoice = await prisma.invoice.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends InvoiceFindUniqueArgs>(args: Prisma.SelectSubset<T, InvoiceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__InvoiceClient<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Invoice that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {InvoiceFindUniqueOrThrowArgs} args - Arguments to find a Invoice
   * @example
   * // Get one Invoice
   * const invoice = await prisma.invoice.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends InvoiceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, InvoiceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__InvoiceClient<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Invoice that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoiceFindFirstArgs} args - Arguments to find a Invoice
   * @example
   * // Get one Invoice
   * const invoice = await prisma.invoice.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends InvoiceFindFirstArgs>(args?: Prisma.SelectSubset<T, InvoiceFindFirstArgs<ExtArgs>>): Prisma.Prisma__InvoiceClient<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Invoice that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoiceFindFirstOrThrowArgs} args - Arguments to find a Invoice
   * @example
   * // Get one Invoice
   * const invoice = await prisma.invoice.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends InvoiceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, InvoiceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__InvoiceClient<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Invoices that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoiceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Invoices
   * const invoices = await prisma.invoice.findMany()
   * 
   * // Get first 10 Invoices
   * const invoices = await prisma.invoice.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const invoiceWithIdOnly = await prisma.invoice.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends InvoiceFindManyArgs>(args?: Prisma.SelectSubset<T, InvoiceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Invoice.
   * @param {InvoiceCreateArgs} args - Arguments to create a Invoice.
   * @example
   * // Create one Invoice
   * const Invoice = await prisma.invoice.create({
   *   data: {
   *     // ... data to create a Invoice
   *   }
   * })
   * 
   */
  create<T extends InvoiceCreateArgs>(args: Prisma.SelectSubset<T, InvoiceCreateArgs<ExtArgs>>): Prisma.Prisma__InvoiceClient<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Invoices.
   * @param {InvoiceCreateManyArgs} args - Arguments to create many Invoices.
   * @example
   * // Create many Invoices
   * const invoice = await prisma.invoice.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends InvoiceCreateManyArgs>(args?: Prisma.SelectSubset<T, InvoiceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Invoice.
   * @param {InvoiceDeleteArgs} args - Arguments to delete one Invoice.
   * @example
   * // Delete one Invoice
   * const Invoice = await prisma.invoice.delete({
   *   where: {
   *     // ... filter to delete one Invoice
   *   }
   * })
   * 
   */
  delete<T extends InvoiceDeleteArgs>(args: Prisma.SelectSubset<T, InvoiceDeleteArgs<ExtArgs>>): Prisma.Prisma__InvoiceClient<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Invoice.
   * @param {InvoiceUpdateArgs} args - Arguments to update one Invoice.
   * @example
   * // Update one Invoice
   * const invoice = await prisma.invoice.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends InvoiceUpdateArgs>(args: Prisma.SelectSubset<T, InvoiceUpdateArgs<ExtArgs>>): Prisma.Prisma__InvoiceClient<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Invoices.
   * @param {InvoiceDeleteManyArgs} args - Arguments to filter Invoices to delete.
   * @example
   * // Delete a few Invoices
   * const { count } = await prisma.invoice.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends InvoiceDeleteManyArgs>(args?: Prisma.SelectSubset<T, InvoiceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Invoices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoiceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Invoices
   * const invoice = await prisma.invoice.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends InvoiceUpdateManyArgs>(args: Prisma.SelectSubset<T, InvoiceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Invoice.
   * @param {InvoiceUpsertArgs} args - Arguments to update or create a Invoice.
   * @example
   * // Update or create a Invoice
   * const invoice = await prisma.invoice.upsert({
   *   create: {
   *     // ... data to create a Invoice
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Invoice we want to update
   *   }
   * })
   */
  upsert<T extends InvoiceUpsertArgs>(args: Prisma.SelectSubset<T, InvoiceUpsertArgs<ExtArgs>>): Prisma.Prisma__InvoiceClient<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Invoices that matches the filter.
   * @param {InvoiceFindRawArgs} args - Select which filters you would like to apply.
   * @example
   * const invoice = await prisma.invoice.findRaw({
   *   filter: { age: { $gt: 25 } }
   * })
   */
  findRaw(args?: Prisma.InvoiceFindRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>

  /**
   * Perform aggregation operations on a Invoice.
   * @param {InvoiceAggregateRawArgs} args - Select which aggregations you would like to apply.
   * @example
   * const invoice = await prisma.invoice.aggregateRaw({
   *   pipeline: [
   *     { $match: { status: "registered" } },
   *     { $group: { _id: "$country", total: { $sum: 1 } } }
   *   ]
   * })
   */
  aggregateRaw(args?: Prisma.InvoiceAggregateRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>


  /**
   * Count the number of Invoices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoiceCountArgs} args - Arguments to filter Invoices to count.
   * @example
   * // Count the number of Invoices
   * const count = await prisma.invoice.count({
   *   where: {
   *     // ... the filter for the Invoices we want to count
   *   }
   * })
  **/
  count<T extends InvoiceCountArgs>(
    args?: Prisma.Subset<T, InvoiceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], InvoiceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Invoice.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoiceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends InvoiceAggregateArgs>(args: Prisma.Subset<T, InvoiceAggregateArgs>): Prisma.PrismaPromise<GetInvoiceAggregateType<T>>

  /**
   * Group by Invoice.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoiceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends InvoiceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: InvoiceGroupByArgs['orderBy'] }
      : { orderBy?: InvoiceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, InvoiceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetInvoiceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Invoice model
 */
readonly fields: InvoiceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Invoice.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__InvoiceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.Invoice$userArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Invoice$userArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Invoice model
 */
export interface InvoiceFieldRefs {
  readonly id: Prisma.FieldRef<"Invoice", 'String'>
  readonly createdAt: Prisma.FieldRef<"Invoice", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Invoice", 'DateTime'>
  readonly slug: Prisma.FieldRef<"Invoice", 'String'>
  readonly paymentDue: Prisma.FieldRef<"Invoice", 'DateTime'>
  readonly paymentTerms: Prisma.FieldRef<"Invoice", 'Int'>
  readonly status: Prisma.FieldRef<"Invoice", 'String'>
  readonly total: Prisma.FieldRef<"Invoice", 'Float'>
  readonly clientName: Prisma.FieldRef<"Invoice", 'String'>
  readonly clientEmail: Prisma.FieldRef<"Invoice", 'String'>
  readonly issued: Prisma.FieldRef<"Invoice", 'DateTime'>
  readonly description: Prisma.FieldRef<"Invoice", 'String'>
  readonly userId: Prisma.FieldRef<"Invoice", 'String'>
}
    

// Custom InputTypes
/**
 * Invoice findUnique
 */
export type InvoiceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceInclude<ExtArgs> | null
  /**
   * Filter, which Invoice to fetch.
   */
  where: Prisma.InvoiceWhereUniqueInput
}

/**
 * Invoice findUniqueOrThrow
 */
export type InvoiceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceInclude<ExtArgs> | null
  /**
   * Filter, which Invoice to fetch.
   */
  where: Prisma.InvoiceWhereUniqueInput
}

/**
 * Invoice findFirst
 */
export type InvoiceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceInclude<ExtArgs> | null
  /**
   * Filter, which Invoice to fetch.
   */
  where?: Prisma.InvoiceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Invoices to fetch.
   */
  orderBy?: Prisma.InvoiceOrderByWithRelationInput | Prisma.InvoiceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Invoices.
   */
  cursor?: Prisma.InvoiceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Invoices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Invoices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Invoices.
   */
  distinct?: Prisma.InvoiceScalarFieldEnum | Prisma.InvoiceScalarFieldEnum[]
}

/**
 * Invoice findFirstOrThrow
 */
export type InvoiceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceInclude<ExtArgs> | null
  /**
   * Filter, which Invoice to fetch.
   */
  where?: Prisma.InvoiceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Invoices to fetch.
   */
  orderBy?: Prisma.InvoiceOrderByWithRelationInput | Prisma.InvoiceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Invoices.
   */
  cursor?: Prisma.InvoiceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Invoices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Invoices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Invoices.
   */
  distinct?: Prisma.InvoiceScalarFieldEnum | Prisma.InvoiceScalarFieldEnum[]
}

/**
 * Invoice findMany
 */
export type InvoiceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceInclude<ExtArgs> | null
  /**
   * Filter, which Invoices to fetch.
   */
  where?: Prisma.InvoiceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Invoices to fetch.
   */
  orderBy?: Prisma.InvoiceOrderByWithRelationInput | Prisma.InvoiceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Invoices.
   */
  cursor?: Prisma.InvoiceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Invoices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Invoices.
   */
  skip?: number
  distinct?: Prisma.InvoiceScalarFieldEnum | Prisma.InvoiceScalarFieldEnum[]
}

/**
 * Invoice create
 */
export type InvoiceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceInclude<ExtArgs> | null
  /**
   * The data needed to create a Invoice.
   */
  data: Prisma.XOR<Prisma.InvoiceCreateInput, Prisma.InvoiceUncheckedCreateInput>
}

/**
 * Invoice createMany
 */
export type InvoiceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Invoices.
   */
  data: Prisma.InvoiceCreateManyInput | Prisma.InvoiceCreateManyInput[]
}

/**
 * Invoice update
 */
export type InvoiceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceInclude<ExtArgs> | null
  /**
   * The data needed to update a Invoice.
   */
  data: Prisma.XOR<Prisma.InvoiceUpdateInput, Prisma.InvoiceUncheckedUpdateInput>
  /**
   * Choose, which Invoice to update.
   */
  where: Prisma.InvoiceWhereUniqueInput
}

/**
 * Invoice updateMany
 */
export type InvoiceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Invoices.
   */
  data: Prisma.XOR<Prisma.InvoiceUpdateManyMutationInput, Prisma.InvoiceUncheckedUpdateManyInput>
  /**
   * Filter which Invoices to update
   */
  where?: Prisma.InvoiceWhereInput
  /**
   * Limit how many Invoices to update.
   */
  limit?: number
}

/**
 * Invoice upsert
 */
export type InvoiceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceInclude<ExtArgs> | null
  /**
   * The filter to search for the Invoice to update in case it exists.
   */
  where: Prisma.InvoiceWhereUniqueInput
  /**
   * In case the Invoice found by the `where` argument doesn't exist, create a new Invoice with this data.
   */
  create: Prisma.XOR<Prisma.InvoiceCreateInput, Prisma.InvoiceUncheckedCreateInput>
  /**
   * In case the Invoice was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.InvoiceUpdateInput, Prisma.InvoiceUncheckedUpdateInput>
}

/**
 * Invoice delete
 */
export type InvoiceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceInclude<ExtArgs> | null
  /**
   * Filter which Invoice to delete.
   */
  where: Prisma.InvoiceWhereUniqueInput
}

/**
 * Invoice deleteMany
 */
export type InvoiceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Invoices to delete
   */
  where?: Prisma.InvoiceWhereInput
  /**
   * Limit how many Invoices to delete.
   */
  limit?: number
}

/**
 * Invoice findRaw
 */
export type InvoiceFindRawArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The query predicate filter. If unspecified, then all documents in the collection will match the predicate. ${@link https://docs.mongodb.com/manual/reference/operator/query MongoDB Docs}.
   */
  filter?: runtime.InputJsonValue
  /**
   * Additional options to pass to the `find` command ${@link https://docs.mongodb.com/manual/reference/command/find/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue
}

/**
 * Invoice aggregateRaw
 */
export type InvoiceAggregateRawArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * An array of aggregation stages to process and transform the document stream via the aggregation pipeline. ${@link https://docs.mongodb.com/manual/reference/operator/aggregation-pipeline MongoDB Docs}.
   */
  pipeline?: runtime.InputJsonValue[]
  /**
   * Additional options to pass to the `aggregate` command ${@link https://docs.mongodb.com/manual/reference/command/aggregate/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue
}

/**
 * Invoice.user
 */
export type Invoice$userArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * Invoice without action
 */
export type InvoiceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceInclude<ExtArgs> | null
}
