
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `InvoiceItem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model InvoiceItem
 * 
 */
export type InvoiceItemModel = runtime.Types.Result.DefaultSelection<Prisma.$InvoiceItemPayload>






export type InvoiceItemCompositeListFilter = {
  equals?: Prisma.InvoiceItemObjectEqualityInput[]
  every?: Prisma.InvoiceItemWhereInput
  some?: Prisma.InvoiceItemWhereInput
  none?: Prisma.InvoiceItemWhereInput
  isEmpty?: boolean
  isSet?: boolean
}

export type InvoiceItemOrderByCompositeAggregateInput = {
  _count?: Prisma.SortOrder
}

export type InvoiceItemListCreateEnvelopeInput = {
  set?: Prisma.InvoiceItemCreateInput | Prisma.InvoiceItemCreateInput[]
}

export type InvoiceItemListUpdateEnvelopeInput = {
  set?: Prisma.InvoiceItemCreateInput | Prisma.InvoiceItemCreateInput[]
  push?: Prisma.InvoiceItemCreateInput | Prisma.InvoiceItemCreateInput[]
  updateMany?: Prisma.InvoiceItemUpdateManyInput
  deleteMany?: Prisma.InvoiceItemDeleteManyInput
}

export type InvoiceItemWhereInput = {
  AND?: Prisma.InvoiceItemWhereInput | Prisma.InvoiceItemWhereInput[]
  OR?: Prisma.InvoiceItemWhereInput[]
  NOT?: Prisma.InvoiceItemWhereInput | Prisma.InvoiceItemWhereInput[]
  id?: Prisma.StringFilter<"InvoiceItem"> | string
  name?: Prisma.StringFilter<"InvoiceItem"> | string
  quantity?: Prisma.IntFilter<"InvoiceItem"> | number
  price?: Prisma.FloatFilter<"InvoiceItem"> | number
  total?: Prisma.FloatFilter<"InvoiceItem"> | number
}

export type InvoiceItemUpdateManyInput = {
  where: Prisma.InvoiceItemWhereInput
  data: Prisma.InvoiceItemUpdateInput
}

export type InvoiceItemDeleteManyInput = {
  where: Prisma.InvoiceItemWhereInput
}

export type InvoiceItemUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  total?: Prisma.FloatFieldUpdateOperationsInput | number
}



export type InvoiceItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  quantity?: boolean
  price?: boolean
  total?: boolean
}, ExtArgs["result"]["invoiceItem"]>



export type InvoiceItemSelectScalar = {
  id?: boolean
  name?: boolean
  quantity?: boolean
  price?: boolean
  total?: boolean
}

export type InvoiceItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "quantity" | "price" | "total", ExtArgs["result"]["invoiceItem"]>

export type $InvoiceItemPayload = {
  name: "InvoiceItem"
  objects: {}
  scalars: {
    id: string
    name: string
    quantity: number
    price: number
    total: number
  }
  composites: {}
}

export type InvoiceItemGetPayload<S extends boolean | null | undefined | InvoiceItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$InvoiceItemPayload, S>





/**
 * Fields of the InvoiceItem model
 */
export interface InvoiceItemFieldRefs {
  readonly id: Prisma.FieldRef<"InvoiceItem", 'String'>
  readonly name: Prisma.FieldRef<"InvoiceItem", 'String'>
  readonly quantity: Prisma.FieldRef<"InvoiceItem", 'Int'>
  readonly price: Prisma.FieldRef<"InvoiceItem", 'Float'>
  readonly total: Prisma.FieldRef<"InvoiceItem", 'Float'>
}
    

// Custom InputTypes
/**
 * InvoiceItem without action
 */
export type InvoiceItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InvoiceItem
   */
  select?: Prisma.InvoiceItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InvoiceItem
   */
  omit?: Prisma.InvoiceItemOmit<ExtArgs> | null
}
