#!/usr/bin/env bash

# Icon export generator - transforms kebab-case to PascalCase
# Usage: ./export-icons.sh [directory]

set -euo pipefail  # Fail fast, fail hard

ICON_DIR="${1:-.}"
OUTPUT_FILE="${ICON_DIR}/index.ts"

# Function to convert kebab-case to PascalCase
kebab_to_pascal() {
    local input="$1"
    # Remove file extension, split on hyphens, capitalize each part
    echo "$input" | sed 's/\.[^.]*$//' | sed 's/-/ /g' | awk '{
        result = ""
        for(i=1; i<=NF; i++) {
            result = result toupper(substr($i,1,1)) tolower(substr($i,2))
        }
        print result
    }'
}

# Validate directory exists
[[ ! -d "$ICON_DIR" ]] && { echo "Directory '$ICON_DIR' not found"; exit 1; }

# Find SVG files and generate exports
{
    echo "/* !!! This is code generated by a script. Do not edit directly. !!! */
/** biome-ignore-all assist/source/organizeImports: generated file */
/** biome-ignore-all lint: generated file */
/* eslint-disable */
// @ts-nocheck
/*
 * This is a barrel export file for all the icons in this directory as React components.
 *
 * 🟢 You can import this file directly.
 * Generated on: $(date)
 */"

    find "$ICON_DIR" -maxdepth 1 -name "*.svg" -type f | sort | while read -r svg_file; do
        filename=$(basename "$svg_file")
        pascal_name="Icon$(kebab_to_pascal "$filename")"

        echo "export { default as $pascal_name } from \"./$filename?component\";"
    done
} > "$OUTPUT_FILE"

echo "Generated exports for $(find "$ICON_DIR" -maxdepth 1 -name "*.svg" -type f | wc -l) icons in $OUTPUT_FILE"
