mutation Register($input: RegisterInput!) {
  register(input: $input) {
    accessToken
    user {
      id
      photo
      firstName
      lastName
    }
  }
}

mutation Login($input: LoginInput!) {
  login(input: $input) {
    accessToken
    user {
      id
      photo
      firstName
      lastName
    }
  }
}

mutation RefreshAuth {
  refreshAuth {
    accessToken
  }
}

mutation Logout {
  logout {
    message
  }
}
